# OK for GARMIN GPS24xd HPS + PPS
# OK for U-BLOX LEA M8T
# difference between PPS from LEA M8T and once through the max232 is:
# delay of 590ns, then a slop from 4.26V to 0V in 1,59us
# -> offset around 2.18us (measured with a scope while RS232-PPS loaded)
refclock SHM 1 refid NMEA offset 2e-6

# To measure the PPS against the ref used to sync
#refclock PPS /dev/pps0 lock NMEA refid PPS noselect

# other PPS examples
#refclock PPS /dev/pps0 lock NMEA refid PPS width 0.100 offset 0.100 precision 1e-5
#refclock PPS /dev/pps0 lock NMEA refid PPS local
#refclock PPS /dev/pps0:clear lock NMEA refid PPS

# PTP hardware clock
#refclock PHC /dev/ptp0 PTP0 local
#refclock PHC /dev/ptp1 PTP1 local
