#!/bin/bash

#GPS_DEV=/dev/ttyTHS1 for jetson
GPS_DEV=/dev/ttyAMA0
GPSD_ADDR=localhost
GPSD_PORT=2947

PPS_DEV=/dev/pps0
# JETSON/RPI Assert only
PPS_EDGE=-A 
PPS_OFFSET_ns=0

DRIFT_PPS_NB=64
OFFSET_PPS_NB=8

