#!/bin/bash

GPS_DEV=/dev/ttyTHS1
GPSD_ADDR=localhost
GPSD_PORT=2947

PPS_DEV=/dev/pps0
# JETSON -Assert only, my gps is on falling edge, 100ms
PPS_EDGE=-A 
PPS_OFFSET_ns=0
#PPS_DELAY_ns=+500000
PPS_DELAY_ns=0
PPS_BETWEEN_SET=900

DRIFT_MIN_ppb=1000
DRIFT_FILE="drift.txt"
LOG_FILE="ppsd.log"

# verif par NTP
NTP_SERVER=ntp.unice.fr

