#!/bin/bash

GPS_DEV=/dev/ttyS0
GPS_SPEED=9600
GPSD_ADDR=localhost
GPSD_PORT=2947
PPS_DEV=/dev/pps0
PPS_EDGE=-C
PPS_OFFSET_ns=0
# on JETSON 200us < PPS fetch delay < 500us 
# on my PC 10us < PPS fetch delay < 200us 
PPS_DELAY_ns=100000
PPS_BEETWEEN_SET=900
#PPS_BEETWEEN_SET=28800
